# Generated by Django 4.2.1 on 2023-08-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
