# Generated by Django 4.2.1 on 2023-07-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_brand'),
        ('store', '0003_rename_prodect_name_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.brand'),
        ),
    ]
