# Generated by Django 4.2.1 on 2023-08-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productvariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('ram', models.ForeignKey(default='Nothig to Show', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product_ram')),
                ('storage', models.ForeignKey(default='Nothing to show', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product_storage')),
            ],
        ),
    ]
