# Generated by Django 4.2.1 on 2023-08-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_ram_product_storage_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='storage',
        ),
        migrations.DeleteModel(
            name='product_ram',
        ),
        migrations.DeleteModel(
            name='product_storage',
        ),
        migrations.DeleteModel(
            name='Productvariant',
        ),
    ]
