# Generated by Django 4.2.1 on 2023-08-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
