# Generated by Django 4.2.3 on 2023-09-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer'),
        ('store', '0010_productvariant_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='offer',
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offer'),
        ),
    ]
