# Generated by Django 4.2.3 on 2023-09-07 13:59

from django.db import migrations, models
import offer.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('off_percent', models.PositiveBigIntegerField()),
                ('start_date', models.DateField(validators=[offer.models.validate_expiry_date])),
                ('end_date', models.DateField()),
            ],
        ),
    ]
