# Generated by Django 4.2.1 on 2023-07-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, upload_to='photos/categoies'),
        ),
    ]
