# Generated by Django 4.2.1 on 2023-07-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_brand'),
        ('category', '0005_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='AdminCategory',
        ),
        migrations.AlterModelOptions(
            name='admincategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
