# Generated by Django 4.2.1 on 2023-07-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_rename_category_admincategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincategory',
            name='category_decs',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
