# Generated by Django 4.2.1 on 2023-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_admincategory_category_decs'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincategory',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
