# Generated by Django 4.2.1 on 2023-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_admincategory_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
