# Generated by Django 4.2.3 on 2023-08-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='fg', max_length=10),
        ),
    ]
