# Generated by Django 4.2.3 on 2023-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_codews',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
