# Generated by Django 4.2.3 on 2023-08-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofile_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referred_by',
        ),
    ]
