# Generated by Django 4.2.3 on 2023-08-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_userprofile_referral_code_userprofile_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referred_by',
        ),
    ]
