# Generated by Django 4.2.3 on 2023-08-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_referral_code_userprofile_referred_by'),
        ('user_profile', '0008_remove_userprofile_referred_by'),
    ]

    operations = [
    ]
