# Generated by Django 4.2.1 on 2023-08-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_price_remove_product_stock'),
        ('order', '0002_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ManyToManyField(null=True, to='store.productvariant'),
        ),
    ]
