# Generated by Django 4.2.1 on 2023-08-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_price_remove_product_stock'),
        ('order', '0003_orderitem_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant'),
        ),
    ]
